#ifndef INCLUDE_ROGUE_COMPONENTS_LIFT_ABILITY_COMPONENT_H_
#define INCLUDE_ROGUE_COMPONENTS_LIFT_ABILITY_COMPONENT_H_

#include "lib/ecs/component.h"
class LiftAbilityComponent : public IComponent {};

#endif  // INCLUDE_ROGUE_COMPONENTS_LIFT_ABILITY_COMPONENT_H_
