#ifndef INCLUDE_ROGUE_COMPONENTS_STATES_REMOVABILITY_COMPONENT_H_
#define INCLUDE_ROGUE_COMPONENTS_STATES_REMOVABILITY_COMPONENT_H_

#include "lib/ecs/component.h"
class RemovabilityComponent : public IComponent {
 public:
};

#endif  // INCLUDE_ROGUE_COMPONENTS_STATES_REMOVABILITY_COMPONENT_H_
