#ifndef INCLUDE_ROGUE_COMPONENTS_TAGS_MANIPULATOR_COMPONENT_H_
#define INCLUDE_ROGUE_COMPONENTS_TAGS_MANIPULATOR_COMPONENT_H_

class Manipulator : public IComponent {};

#endif  // INCLUDE_ROGUE_COMPONENTS_TAGS_MANIPULATOR_COMPONENT_H_
