#ifndef INCLUDE_ROGUE_COMPONENTS_TAGS_TARGET_COMPONENT_H_
#define INCLUDE_ROGUE_COMPONENTS_TAGS_TARGET_COMPONENT_H_

#include "lib/ecs/component.h"
class TargetComponent : public IComponent {};

#endif  // INCLUDE_ROGUE_COMPONENTS_TAGS_TARGET_COMPONENT_H_
